version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      npm-production:
        dependency-type: "production"
      npm-development:
        dependency-type: "development"
    ignore:
      - dependency-name: "typescript"
        versions: [">=7.0.0 <8.0.0"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
