############################ Default configuration #########################
baseurl = "https://www.acevedommiguel.com/"
languageCode = "en-us"
title = "Personal Resume for Acevedo Miguel Angel | acevedomiguel.com"
theme = "acevedomiguel"
canonifyurls = true

[outputs]
home = ["HTML", "AMP", "RSS"]

######################### Default Parameters ###########################
[params]
# url = "https://www.acevedommiguel.com/"
twitter = "faultydev"
facebook = "acevedomiguel"
linkedin = "acevedomiguel"
email = "me@acevedomiguel.com"
address = "Yau Ma Tei, Kowloon, Hong Kong"
phone = "+852 6435 6936"
cvFile= "acevedo-miguel-cv-2021-08.pdf"
home = "Home"
logo = "images/logo.svg"
author = "Themefisher"
description = "This is meta description"

# preloader
[params.preloader]
enable = true
preloader = "" # use png, jpg, svg or gif format