name: Features

on:
  push:
    branches: 
      - features/*
      - feature/*
      - feat/*
      - bug/*
      - hotfix/*

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  deploy:
    uses: ./.github/workflows/common.yaml
    secrets: inherit
    with:
      environment: preview
      site_url: https://preview.acevedomiguel.com