name: Features

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  deploy:
    uses: ./.github/workflows/common.yaml
    secrets: inherit
    with:
      environment: preview
      site_url: https://preview.acevedomiguel.com