name: Features CI

on:
  push:
    branches: [ features/* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      env:
        SITE_URL: https://staging.acevedomiguel.com/
      with:
        node-version: 12
    - run: npm ci
    - run: npm run build

    - name: rsync deployments
      run: |
        mkdir ~/.ssh
        echo "$remote_key" > ~/.ssh/gh_actions_key
        chmod 600 ~/.ssh/gh_actions_key
        rsync -avz --exclude '.git' --exclude '.well-known' -e "ssh -i ~/.ssh/gh_actions_key -o StrictHostKeyChecking=no" out/ $remote_user@$remote_host:$remote_path
      env:
        remote_path: ${{ secrets.TESTING_REMOTE_PATH }}
        remote_host: ${{ secrets.TESTING_REMOTE_HOST }}
        remote_user: ${{ secrets.TESTING_REMOTE_USER }}
        remote_key: ${{ secrets.TESTING_DEPLOY_KEY }}
