name: Production CI

on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/common.yaml
    secrets: inherit
    with:
      environment: production
      ga_code: G-FF211XJ57Q
      site_url: https://www.acevedomiguel.com